### ISSUE TITLE
telegraf in so-telegraf doesn't reap zombie processes, forward node crashes

### ISSUE THREAD

**Issue by jtgreen-cse** [Security-Onion-Solutions/securityonion#2293]
I've been seeing our sensor nodes crash after multiple days of running. I've traced it to processes not being able to fork after the thread IDs get exhausted. On a running sensor node I can run `ps -ef` and see zombie `stenoloss.sh` processes accumulating. These accumulate at 1 a minute, the time telegraf runs it's scripts.

Did some research and seems this was a bug in telegraf and was eventually fixed in 1.13.

https://github.com/influxdata/telegraf/issues/2820

In so-telegraf:

```
Telegraf 1.10.1 (git: HEAD a6778f46)
bash-5.0#
```

- duplicated the issue on a fresh installation of the latest version
This is a bug inside the so-telegraf container

- provide information about your system and how you installed Security Onion
Ubuntu 18.04
Distributed

- include relevant log files

Inside so-telegraf:

```
root         1     0  0 11:13 ?        00:00:05 telegraf
root        62     1  0 11:13 ?        00:00:00 [stenoloss.sh] <defunct>
root       112     1  0 11:13 ?        00:00:00 [stenoloss.sh] <defunct>
root       141     1  0 11:14 ?        00:00:00 [stenoloss.sh] <defunct>
root       215     1  0 11:14 ?        00:00:00 [stenoloss.sh] <defunct>
root       233     1  0 11:15 ?        00:00:00 [stenoloss.sh] <defunct>
root       292     1  0 11:15 ?        00:00:00 [stenoloss.sh] <defunct>
root       329     1  0 11:16 ?        00:00:00 [stenoloss.sh] <defunct>
root       379     1  0 11:16 ?        00:00:00 [stenoloss.sh] <defunct>
root       437     1  0 11:17 ?        00:00:00 [stenoloss.sh] <defunct>
root       448     0  0 11:17 pts/0    00:00:00 bash
root       479     1  0 11:17 ?        00:00:00 [stenoloss.sh] <defunct>
root       529     1  0 11:18 ?        00:00:00 [stenoloss.sh] <defunct>
root       586     1  0 11:18 ?        00:00:00 [stenoloss.sh] <defunct>
root       655     1  0 11:19 ?        00:00:00 [stenoloss.sh] <defunct>
root       727     1  0 11:19 ?        00:00:00 [stenoloss.sh] <defunct>
root       839     1  0 11:20 ?        00:00:00 [stenoloss.sh] <defunct>
root       872     1  0 11:21 ?        00:00:00 [stenoloss.sh] <defunct>
root       928     1  0 11:21 ?        00:00:00 [stenoloss.sh] <defunct>
root       973     1  0 11:22 ?        00:00:00 [stenoloss.sh] <defunct>
root      1017     1  0 11:22 ?        00:00:00 [stenoloss.sh] <defunct>
root      1087     1  0 11:23 ?        00:00:00 [stenoloss.sh] <defunct>
root      1108     1  0 11:23 ?        00:00:00 [stenoloss.sh] <defunct>
root      1161     1  0 11:24 ?        00:00:00 [stenoloss.sh] <defunct>
root      1229     1  0 11:24 ?        00:00:00 [stenoloss.sh] <defunct>
root      1312     1  0 11:25 ?        00:00:00 [stenoloss.sh] <defunct>
root      1353     1  0 11:25 ?        00:00:00 [stenoloss.sh] <defunct>
root      1401     1  0 11:26 ?        00:00:00 [stenoloss.sh] <defunct>
root      1442     1  0 11:26 ?        00:00:00 [stenoloss.sh] <defunct>
root      1485     1  0 11:27 ?        00:00:00 [stenoloss.sh] <defunct>
root      1529     1  0 11:27 ?        00:00:00 [stenoloss.sh] <defunct>
root      1574     1  0 11:28 ?        00:00:00 [stenoloss.sh] <defunct>
root      1685     1  0 11:29 ?        00:00:00 [stenoloss.sh] <defunct>
root      1739     1  0 11:29 ?        00:00:00 [stenoloss.sh] <defunct>
root      1773     1  0 11:30 ?        00:00:00 [stenoloss.sh] <defunct>
root      1813     1  0 11:30 ?        00:00:00 [stenoloss.sh] <defunct>
root      1884     1  0 11:31 ?        00:00:00 [stenoloss.sh] <defunct>
root      1910     1  0 11:31 ?        00:00:00 [stenoloss.sh] <defunct>
root      1951     1  0 11:32 ?        00:00:00 [stenoloss.sh] <defunct>
root      2001     1  0 11:32 ?        00:00:00 [stenoloss.sh] <defunct>
root      2058     1  0 11:33 ?        00:00:00 [stenoloss.sh] <defunct>
root      2097     1  0 11:33 ?        00:00:00 [stenoloss.sh] <defunct>
root      2131     1  0 11:34 ?        00:00:00 [stenoloss.sh] <defunct>
root      2192     1  0 11:34 ?        00:00:00 [stenoloss.sh] <defunct>
root      2260     1  0 11:35 ?        00:00:00 [stenoloss.sh] <defunct>
root      2323     1  0 11:35 ?        00:00:00 [stenoloss.sh] <defunct>
root      2366     1  0 11:36 ?        00:00:00 [stenoloss.sh] <defunct>
root      2406     1  0 11:36 ?        00:00:00 [stenoloss.sh] <defunct>

```

- include reproduction steps
Let the system run, eventually all thread IDs will be consumed and system will come screeching to a halt.

**Comment by TOoSmOotH** [comment]
Are you running 2.3.10? This was fixed on that release.

**Comment by jtgreen-cse** [comment]
I am running 2.3.10.

`manager:5000/securityonion/so-telegraf:2.3.10`

**Comment by jtgreen-cse** [comment]
Not sure what the fix was but the so-telegraf Dockerfile still wants 1.10.1:

https://github.com/Security-Onion-Solutions/securityonion-image/blob/6d917db3d5615a695e15c98eb69a82c39ba9e4c5/so-telegraf/Dockerfile#L9

**Comment by jtgreen-cse** [comment]
Running 2.3.21, this issue is still occurring and is still taking down our sensor nodes when the process limit is reached if `so-telegraf` isn't periodically restarted. I have a feeling this is an Ubuntu only thing (therefore not as pervalent) since this isn't happening on a .iso installed grid.

**Comment by jtgreen-cse** [comment]
Should I create a new issue or can we reopen this? @TOoSmOotH

**Comment by jtgreen-cse** [comment]
`so-telegraf` doesn't use an init process, this causes zombie processes to accumulate if `telegraf` ends up killing a script. The original proposed fix was to move to the latest `telegraf`, this was informed by this issue:

https://github.com/influxdata/telegraf/issues/2820

however, I misread the issue. I thought they fixed reaping processes in __telegraf__ __1.13__ but they chose **not** to make telegraf reap since __docker__ has `--init` as of __1.13__ (`--init` adds an init process before `entrypoint`).

Zombie processes should not be able to take down a node, so I think an init process should be inserted in `so-telegraf`'s `entrypoint.sh` (ideally salt should get support to pass `--init` in `docker_container.running`, but currently doesn't) however, the actual cause of the zombie processes is the `stenoloss.sh` script. Since the commands are the busybox equivalents inside the alpine container, they don't perform as well as the GNU ones, so the combination of `tac` and `grep -m 1` end up reading the entire file. `stenographer.log` sits at 1.4G on one of my nodes currently and takes 9 seconds to read, that's longer than the default 5 seconds timeout for `telegraf`, which kills it .. and well .. we know what happens then.

I believe in:

https://github.com/Security-Onion-Solutions/securityonion/blob/36207d04409c5ad007c51bc6bb7a3862884dca26/salt/telegraf/scripts/stenoloss.sh#L35

`tail -n 100 /var/log/stenographer/stenographer.log | tac | grep -m 1` would perform better and solves it for a log file of at least 1.4G.

**Comment by rwwiv** [comment]
@jtgreen-cse we've made changes to telegraf's config and salt state that will address this issue in the next release. See 4079f8a and f1781b1.

**Comment by jtgreen-cse** [comment]
Good fix so it doesn't take down the node, but as soon as the `stenographer.log` gets to a size that the script takes more that 15 seconds to read the file, you'll lose that graph in grafana. I'm assuming we'll need to realize that and change the `timeout:`?

**Comment by rwwiv** [comment]
We've also added `stenographer.log` file to the global logrotate job to prevent long read times. (See 8cca792)
